### ISSUE TITLE
integrate L.TileLayer.Swiss with https://github.com/lao-tseu-is-alive/lausanne-map-wmts-mn95

### ISSUE THREAD

**Issue by lperozzi** [rkaravia/Leaflet.TileLayer.Swiss#11]
I use  this set of WMTS lausanne maps https://tilesmn95.lausanne.ch/. 
I would like to add the swissimage layer using L.TileLayer.Swiss and switch between the Lausanne's and Swissimage's layers.
From the documentation page, the resolution of lausanne tiles is `[50,20,10,5,2.5,1,0.5,0.25,0.1,0.05]` which is not exactely the same as the  Swisstopo's.
On lealfet.tileLayer there is an option called [ZoomOffset](https://leafletjs.com/reference.html#tilelayer-zoomoffset) to offset the zoom value, but since the resolution after 2.5 differe between the two maps, i'm unable to superpose the layers. 
Have you some hints to achieve that superposition?

**Comment by rkaravia** [comment]
Yes, I was curious if this could actually work and made an example:
- [Live demo](https://leaflet-tilelayer-swiss.karavia.ch/examples/experimental/lausanne-tiles)
- Source code [HTML](https://github.com/rkaravia/Leaflet.TileLayer.Swiss/blob/1fa2db49be6cfe80d60b956d15870a93ce9a4f13/docs/examples/experimental/lausanne-tiles.html) / [JS](https://github.com/rkaravia/Leaflet.TileLayer.Swiss/blob/1fa2db49be6cfe80d60b956d15870a93ce9a4f13/docs/examples/experimental/lausanne-tiles.js)

[<img src="https://github.com/rkaravia/Leaflet.TileLayer.Swiss/assets/3082173/57a06865-6ef3-4886-a93a-e20f8d81ee54" alt="Screenshot" width="640">](https://leaflet-tilelayer-swiss.karavia.ch/examples/experimental/lausanne-tiles)

There's basically 2 questions hidden in there:
- How do you set custom resolutions for the Swiss CRS (coordinate reference system) that are provided by this plugin? Someone already asked for this (#6), and I would like to make it easier to do this in the future. Currently, it's possible by duplicating some code from `src/resolution.js` / `src/crs.js`. This is required to display the Lausanne tiles, even before thinking about combining them with Swisstopo tiles.
- How do you combine Lausanne + Swisstopo tiles? In general, it is not possible to use 2 different CRS with Leaflet (or maybe with [some hacks](https://gis.stackexchange.com/a/61396), but probably not a good idea). However, in this particular case, the 2 CRS are very similar, we just need to skip 2 zoom levels for the Swisstopo tiles:
  - For zoom level 22, show tiles with resolution 2.5 meters per pixel, replace `{z}` by `22` for both Lausanne and Swisstopo tile URLs
  - For zoom level 23, show tiles with resolution 1 m/px, replace `{z}` by `23` for Lausanne tiles, and replace `{z}` by 25 for Swisstopo tiles => this requires special handling
  - For zoom level 24+ similarly replace `{z}` by `zoom level + 2` for Swisstopo tiles

**Comment by lperozzi** [comment]
@rkaravia,

amazing, thanks. However, I'm now unable to load WMS (which are served from geoserver):

```
export const wmslayer = L.tileLayer.wms("http://example.com:8080/geoserver/ows/", {
        layers: 'project:wmsexemple',
        format: 'image/png',
        transparent: true,
        // version: '1.1.1',
        opacity: 0.3,
});
```
I tried to set `customSwissCrs` as a custom crs, but it doesn't work. Should I create a new constructor for the WMS, which skip the resolutions?

**Comment by rkaravia** [comment]
Is the snipped you posted part of a project that is published somewhere or do you mind publishing a small sample of what you have tried? Otherwise it's a bit difficult to figure out what is going wrong.

It's possible that your problem is related to the fact that WMS layers in Leaflet have `maxzoom: 18` by default, maybe setting a higher value will already make it work, see also discussion in #9.
