### ISSUE TITLE
Is it possible to mix different projection

### ISSUE THREAD

**Issue by Deneb77** [rkaravia/Leaflet.TileLayer.Swiss#5]
Hello,

Nice plugin !

Is it possible to mix different projection system ?
Example : Showing lat lng (WGS84 / SRID 4326) GeoJSON on top of swiss map ?

Best regards,

DE

**Comment by rkaravia** [comment]
Yes, I happen to have an (undocumented) example for that exact use case here:
https://labs.karavia.ch/geojson-swiss/?options={"trackUrl":"https://karavia.ch/data/20km.geojson"}

As you can see, the GeoJSON is in standard WGS84 format: https://karavia.ch/data/20km.geojson

See also: [source code of the example](https://github.com/rkaravia/geojson-swiss)

For GeoJSON data in any other projection, you would have to transform it to WGS84 before displaying it.

**Comment by Deneb77** [comment]
Great thx,
one more question is it also possible to use on the same map:
one tilemap from swiss projection system
and another tile map somehting like openstreetmap that use "googlemap" like projection ?
