### ISSUE TITLE
error message after integrating the script: Leaflet.TileLayer.Swiss.umd.js

### ISSUE THREAD

**Issue by strukturart** [rkaravia/Leaflet.TileLayer.Swiss#7]
```
projection.js:6 Uncaught TypeError: n.default.bounds is not a function
    at projection.js:6:23
    at Leaflet.TileLayer.Swiss.umd.js:7:283
    at Leaflet.TileLayer.Swiss.umd.js:7:291
```

**Comment by rkaravia** [comment]
Sorry, there is not enough information here to understand where this error comes from, I assume you are not just loading the script, but trying to call some functions from the library which cause the error.

Please open a new issue with a more detailed description how to reproduce the error, ideally with a link to a reproducible example somewhere.
